using Game.Models;

namespace Game.Core
{
    public static class ReactionDatabase
    {
        public static ReactionData[][] GetPredefinedPools()
        {
            return new[] { EasyPool, NormalPool, HardPool, ImpossiblePool };
        }

        private static readonly ReactionData[] EasyPool = new[] {
            new ReactionData(new[] { new ChemicalComponent("H2", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("H2O", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("C", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("CO2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("MgO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("S", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("SO2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("P", 4), new ChemicalComponent("O2", 5) }, new[] { new ChemicalComponent("P2O5", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("CaO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Na", 4), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("Na2O", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("K", 4), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("K2O", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("Al2O3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Fe", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("Fe2O3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Cu", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("CuO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Zn", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("ZnO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Li", 4), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("Li2O", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ba", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("BaO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Si", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("SiO2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("N2", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("NO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("B", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("B2O3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2", 1), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("HCl", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2", 1), new ChemicalComponent("Br2", 1) }, new[] { new ChemicalComponent("HBr", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2", 1), new ChemicalComponent("I2", 1) }, new[] { new ChemicalComponent("HI", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2", 1), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("H2S", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Na", 2), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("Na2S", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("K", 2), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("K2S", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 1), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("CaS", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("MgS", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Fe", 1), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("FeS", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("CuS", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("S", 1) }, new[] { new ChemicalComponent("ZnS", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("S", 3) }, new[] { new ChemicalComponent("Al2S3", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Na", 2), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("NaCl", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("K", 2), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("KCl", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("MgCl2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 1), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("CaCl2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("ZnCl2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("CuCl2", 1) }, Difficulty.Easy),

            new ReactionData(new[] { new ChemicalComponent("Li", 2), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("LiCl", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ba", 1), new ChemicalComponent("Cl2", 1) }, new[] { new ChemicalComponent("BaCl2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Fe", 2), new ChemicalComponent("Cl2", 3) }, new[] { new ChemicalComponent("FeCl3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("Cl2", 3) }, new[] { new ChemicalComponent("AlCl3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("P", 2), new ChemicalComponent("Cl2", 3) }, new[] { new ChemicalComponent("PCl3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("P", 2), new ChemicalComponent("Cl2", 5) }, new[] { new ChemicalComponent("PCl5", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("C", 1), new ChemicalComponent("Cl2", 2) }, new[] { new ChemicalComponent("CCl4", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Si", 1), new ChemicalComponent("Cl2", 2) }, new[] { new ChemicalComponent("SiCl4", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Na", 2), new ChemicalComponent("Br2", 1) }, new[] { new ChemicalComponent("NaBr", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("K", 2), new ChemicalComponent("Br2", 1) }, new[] { new ChemicalComponent("KBr", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("Br2", 1) }, new[] { new ChemicalComponent("MgBr2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 1), new ChemicalComponent("Br2", 1) }, new[] { new ChemicalComponent("CaBr2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("Br2", 3) }, new[] { new ChemicalComponent("AlBr3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("Br2", 1) }, new[] { new ChemicalComponent("ZnBr2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Fe", 2), new ChemicalComponent("Br2", 3) }, new[] { new ChemicalComponent("FeBr3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Na", 2), new ChemicalComponent("I2", 1) }, new[] { new ChemicalComponent("NaI", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("K", 2), new ChemicalComponent("I2", 1) }, new[] { new ChemicalComponent("KI", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("I2", 1) }, new[] { new ChemicalComponent("MgI2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 1), new ChemicalComponent("I2", 1) }, new[] { new ChemicalComponent("CaI2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("I2", 3) }, new[] { new ChemicalComponent("AlI3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("I2", 1) }, new[] { new ChemicalComponent("ZnI2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("N2", 1), new ChemicalComponent("H2", 3) }, new[] { new ChemicalComponent("NH3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Li", 3), new ChemicalComponent("N2", 1) }, new[] { new ChemicalComponent("Li3N", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 3), new ChemicalComponent("N2", 1) }, new[] { new ChemicalComponent("Mg3N2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 3), new ChemicalComponent("N2", 1) }, new[] { new ChemicalComponent("Ca3N2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 1), new ChemicalComponent("N2", 1) }, new[] { new ChemicalComponent("AlN", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("C", 1), new ChemicalComponent("H2", 2) }, new[] { new ChemicalComponent("CH4", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Si", 1), new ChemicalComponent("H2", 2) }, new[] { new ChemicalComponent("SiH4", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ca", 1), new ChemicalComponent("C", 2) }, new[] { new ChemicalComponent("CaC2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Al", 4), new ChemicalComponent("C", 3) }, new[] { new ChemicalComponent("Al4C3", 1) }, Difficulty.Easy),

            new ReactionData(new[] { new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("H2", 2), new ChemicalComponent("O2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("HgO", 2) }, new[] { new ChemicalComponent("Hg", 2), new ChemicalComponent("O2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("CuO", 2) }, new[] { new ChemicalComponent("Cu", 2), new ChemicalComponent("O2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Au2O3", 2) }, new[] { new ChemicalComponent("Au", 4), new ChemicalComponent("O2", 3) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Ag2O", 2) }, new[] { new ChemicalComponent("Ag", 4), new ChemicalComponent("O2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("CO", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("CO2", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("SO2", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("SO3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("NO", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("NO2", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("C", 1) }, new[] { new ChemicalComponent("CO", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Fe", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("FeO", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("As", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("As2O3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("As", 4), new ChemicalComponent("O2", 5) }, new[] { new ChemicalComponent("As2O5", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Sb", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("Sb2O3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Sb", 4), new ChemicalComponent("O2", 5) }, new[] { new ChemicalComponent("Sb2O5", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Bi", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("Bi2O3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Se", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("SeO2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Te", 1), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("TeO2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Mg", 2), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("MgO", 2), new ChemicalComponent("C", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("Na", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("Na2O2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("K", 2), new ChemicalComponent("O2", 1) }, new[] { new ChemicalComponent("K2O2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("SO3", 1) }, new[] { new ChemicalComponent("H2SO4", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("H2CO3", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("SO2", 1) }, new[] { new ChemicalComponent("H2SO3", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("N2O5", 1) }, new[] { new ChemicalComponent("HNO3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 3), new ChemicalComponent("P2O5", 1) }, new[] { new ChemicalComponent("H3PO4", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("P2O5", 1) }, new[] { new ChemicalComponent("HPO3", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("Na2O", 1) }, new[] { new ChemicalComponent("NaOH", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("K2O", 1) }, new[] { new ChemicalComponent("KOH", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("CaO", 1) }, new[] { new ChemicalComponent("Ca(OH)2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("BaO", 1) }, new[] { new ChemicalComponent("Ba(OH)2", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2O", 1), new ChemicalComponent("Li2O", 1) }, new[] { new ChemicalComponent("LiOH", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("HCl", 1), new ChemicalComponent("NH3", 1) }, new[] { new ChemicalComponent("NH4Cl", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("HNO3", 1), new ChemicalComponent("NH3", 1) }, new[] { new ChemicalComponent("NH4NO3", 1) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("H2S", 2), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("SO2", 2), new ChemicalComponent("H2O", 2) }, Difficulty.Easy),
            new ReactionData(new[] { new ChemicalComponent("CH4", 1), new ChemicalComponent("O2", 2) }, new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Easy)
        };

        private static readonly ReactionData[] NormalPool = new[] {
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("ZnCl2", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("MgCl2", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("FeCl2", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("HCl", 6) }, new[] { new ChemicalComponent("AlCl3", 2), new ChemicalComponent("H2", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Na", 2), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("NaOH", 2), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("K", 2), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("KOH", 2), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Li", 2), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("LiOH", 2), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ca", 1), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("Ca(OH)2", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ba", 1), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("Ba(OH)2", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("ZnSO4", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("MgSO4", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("FeSO4", 1), new ChemicalComponent("H2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("Al2(SO4)3", 1), new ChemicalComponent("H2", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe", 1), new ChemicalComponent("CuSO4", 1) }, new[] { new ChemicalComponent("FeSO4", 1), new ChemicalComponent("Cu", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("CuSO4", 1) }, new[] { new ChemicalComponent("ZnSO4", 1), new ChemicalComponent("Cu", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("AgNO3", 2) }, new[] { new ChemicalComponent("Cu(NO3)2", 1), new ChemicalComponent("Ag", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("Pb(NO3)2", 1) }, new[] { new ChemicalComponent("Zn(NO3)2", 1), new ChemicalComponent("Pb", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Mg", 1), new ChemicalComponent("FeCl2", 1) }, new[] { new ChemicalComponent("MgCl2", 1), new ChemicalComponent("Fe", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("H2O2", 2) }, new[] { new ChemicalComponent("H2O", 2), new ChemicalComponent("O2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KClO3", 2) }, new[] { new ChemicalComponent("KCl", 2), new ChemicalComponent("O2", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2) }, new[] { new ChemicalComponent("K2MnO4", 1), new ChemicalComponent("MnO2", 1), new ChemicalComponent("O2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CaCO3", 1) }, new[] { new ChemicalComponent("CaO", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("MgCO3", 1) }, new[] { new ChemicalComponent("MgO", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("BaCO3", 1) }, new[] { new ChemicalComponent("BaO", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Cu2(OH)2CO3", 1) }, new[] { new ChemicalComponent("CuO", 2), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe3O4", 1), new ChemicalComponent("H2", 4) }, new[] { new ChemicalComponent("Fe", 3), new ChemicalComponent("H2O", 4) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CuO", 1), new ChemicalComponent("H2", 1) }, new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("WO3", 1), new ChemicalComponent("H2", 3) }, new[] { new ChemicalComponent("W", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe2O3", 1), new ChemicalComponent("H2", 3) }, new[] { new ChemicalComponent("Fe", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CuO", 1), new ChemicalComponent("C", 1) }, new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("CO", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe2O3", 1), new ChemicalComponent("C", 3) }, new[] { new ChemicalComponent("Fe", 2), new ChemicalComponent("CO", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("ZnO", 1), new ChemicalComponent("C", 1) }, new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("CO", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("PbO", 1), new ChemicalComponent("C", 1) }, new[] { new ChemicalComponent("Pb", 1), new ChemicalComponent("CO", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("SnO2", 1), new ChemicalComponent("C", 2) }, new[] { new ChemicalComponent("Sn", 1), new ChemicalComponent("CO", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("SiO2", 1), new ChemicalComponent("C", 2) }, new[] { new ChemicalComponent("Si", 1), new ChemicalComponent("CO", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("H2", 1) }, new[] { new ChemicalComponent("CO", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("C2H4", 1), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("CO2", 2), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("C2H2", 2), new ChemicalComponent("O2", 5) }, new[] { new ChemicalComponent("CO2", 4), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CH3OH", 2), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("CO2", 2), new ChemicalComponent("H2O", 4) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("C2H5OH", 1), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("CO2", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),

            new ReactionData(new[] { new ChemicalComponent("NaOH", 1), new ChemicalComponent("HCl", 1) }, new[] { new ChemicalComponent("NaCl", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KOH", 1), new ChemicalComponent("HCl", 1) }, new[] { new ChemicalComponent("KCl", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ca(OH)2", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("CaCl2", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ba(OH)2", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("BaCl2", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("NaOH", 1), new ChemicalComponent("HNO3", 1) }, new[] { new ChemicalComponent("NaNO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KOH", 1), new ChemicalComponent("HNO3", 1) }, new[] { new ChemicalComponent("KNO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("NaOH", 2), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("Na2SO4", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KOH", 2), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ba(OH)2", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("BaSO4", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ca(OH)2", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("CaSO4", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CuO", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("CuCl2", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CuO", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("CuSO4", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe2O3", 1), new ChemicalComponent("HCl", 6) }, new[] { new ChemicalComponent("FeCl3", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe2O3", 1), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("Fe2(SO4)3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("MgO", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("MgCl2", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("MgO", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("MgSO4", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("ZnO", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("ZnCl2", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("ZnO", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("ZnSO4", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Al2O3", 1), new ChemicalComponent("HCl", 6) }, new[] { new ChemicalComponent("AlCl3", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Al2O3", 1), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("Al2(SO4)3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("AgNO3", 1), new ChemicalComponent("HCl", 1) }, new[] { new ChemicalComponent("AgCl", 1), new ChemicalComponent("HNO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("AgNO3", 1), new ChemicalComponent("NaCl", 1) }, new[] { new ChemicalComponent("AgCl", 1), new ChemicalComponent("NaNO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("BaCl2", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("BaSO4", 1), new ChemicalComponent("HCl", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("BaCl2", 1), new ChemicalComponent("Na2SO4", 1) }, new[] { new ChemicalComponent("BaSO4", 1), new ChemicalComponent("NaCl", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CaCl2", 1), new ChemicalComponent("Na2CO3", 1) }, new[] { new ChemicalComponent("CaCO3", 1), new ChemicalComponent("NaCl", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("BaCl2", 1), new ChemicalComponent("K2CO3", 1) }, new[] { new ChemicalComponent("BaCO3", 1), new ChemicalComponent("KCl", 2) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CuSO4", 1), new ChemicalComponent("NaOH", 2) }, new[] { new ChemicalComponent("Cu(OH)2", 1), new ChemicalComponent("Na2SO4", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("FeCl3", 1), new ChemicalComponent("NaOH", 3) }, new[] { new ChemicalComponent("Fe(OH)3", 1), new ChemicalComponent("NaCl", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("AlCl3", 1), new ChemicalComponent("KOH", 3) }, new[] { new ChemicalComponent("Al(OH)3", 1), new ChemicalComponent("KCl", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("ZnSO4", 1), new ChemicalComponent("NaOH", 2) }, new[] { new ChemicalComponent("Zn(OH)2", 1), new ChemicalComponent("Na2SO4", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CaCO3", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("CaCl2", 1), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Na2CO3", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("NaCl", 2), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("K2CO3", 1), new ChemicalComponent("HNO3", 2) }, new[] { new ChemicalComponent("KNO3", 2), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Na2SO3", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("NaCl", 2), new ChemicalComponent("H2O", 1), new ChemicalComponent("SO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("K2SO3", 1), new ChemicalComponent("H2SO4", 1) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("H2O", 1), new ChemicalComponent("SO2", 1) }, Difficulty.Normal),

            new ReactionData(new[] { new ChemicalComponent("NH4Cl", 1), new ChemicalComponent("NaOH", 1) }, new[] { new ChemicalComponent("NaCl", 1), new ChemicalComponent("NH3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe(OH)2", 1) }, new[] { new ChemicalComponent("FeO", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe(OH)3", 2) }, new[] { new ChemicalComponent("Fe2O3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Al(OH)3", 2) }, new[] { new ChemicalComponent("Al2O3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Cu(OH)2", 1) }, new[] { new ChemicalComponent("CuO", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("H2SiO3", 1) }, new[] { new ChemicalComponent("SiO2", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Na2O", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("Na2CO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("K2O", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("K2CO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CaO", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("CaCO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("BaO", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("BaCO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Na2O", 1), new ChemicalComponent("SO3", 1) }, new[] { new ChemicalComponent("Na2SO4", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("K2O", 1), new ChemicalComponent("SO3", 1) }, new[] { new ChemicalComponent("K2SO4", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("CaO", 1), new ChemicalComponent("SO3", 1) }, new[] { new ChemicalComponent("CaSO4", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("BaO", 1), new ChemicalComponent("SO3", 1) }, new[] { new ChemicalComponent("BaSO4", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("NaOH", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("NaHCO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KOH", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("KHCO3", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("NaOH", 2), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("Na2CO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KOH", 2), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("K2CO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ca(OH)2", 1), new ChemicalComponent("CO2", 2) }, new[] { new ChemicalComponent("Ca(NaHCO3)2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ca(OH)2", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("CaCO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ba(OH)2", 1), new ChemicalComponent("CO2", 1) }, new[] { new ChemicalComponent("BaCO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("NaHCO3", 2) }, new[] { new ChemicalComponent("Na2CO3", 1), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("KHCO3", 2) }, new[] { new ChemicalComponent("K2CO3", 1), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Ca(HCO3)2", 1) }, new[] { new ChemicalComponent("CaCO3", 1), new ChemicalComponent("H2O", 1), new ChemicalComponent("CO2", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("FeS", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("FeCl2", 1), new ChemicalComponent("H2S", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("ZnS", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("ZnCl2", 1), new ChemicalComponent("H2S", 1) }, Difficulty.Normal),
            new ReactionData(new[] { new ChemicalComponent("Fe2O3", 1), new ChemicalComponent("Al", 2) }, new[] { new ChemicalComponent("Al2O3", 1), new ChemicalComponent("Fe", 2) }, Difficulty.Normal)
        };

        private static readonly ReactionData[] HardPool = new[] {
            new ReactionData(new[] { new ChemicalComponent("C3H8", 1), new ChemicalComponent("O2", 5) }, new[] { new ChemicalComponent("CO2", 3), new ChemicalComponent("H2O", 4) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C4H10", 2), new ChemicalComponent("O2", 13) }, new[] { new ChemicalComponent("CO2", 8), new ChemicalComponent("H2O", 10) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C5H12", 1), new ChemicalComponent("O2", 8) }, new[] { new ChemicalComponent("CO2", 5), new ChemicalComponent("H2O", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C6H6", 2), new ChemicalComponent("O2", 15) }, new[] { new ChemicalComponent("CO2", 12), new ChemicalComponent("H2O", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C7H8", 1), new ChemicalComponent("O2", 9) }, new[] { new ChemicalComponent("CO2", 7), new ChemicalComponent("H2O", 4) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C2H6O", 1), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("CO2", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C3H8O", 2), new ChemicalComponent("O2", 9) }, new[] { new ChemicalComponent("CO2", 6), new ChemicalComponent("H2O", 8) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C6H12O6", 1), new ChemicalComponent("O2", 6) }, new[] { new ChemicalComponent("CO2", 6), new ChemicalComponent("H2O", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("C12H22O11", 1), new ChemicalComponent("O2", 12) }, new[] { new ChemicalComponent("CO2", 12), new ChemicalComponent("H2O", 11) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NH3", 4), new ChemicalComponent("O2", 5) }, new[] { new ChemicalComponent("NO", 4), new ChemicalComponent("H2O", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NH3", 4), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("N2", 2), new ChemicalComponent("H2O", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("H2S", 2), new ChemicalComponent("SO2", 1) }, new[] { new ChemicalComponent("S", 3), new ChemicalComponent("H2O", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("FeS2", 4), new ChemicalComponent("O2", 11) }, new[] { new ChemicalComponent("Fe2O3", 2), new ChemicalComponent("SO2", 8) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("ZnS", 2), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("ZnO", 2), new ChemicalComponent("SO2", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CuS", 2), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("CuO", 2), new ChemicalComponent("SO2", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("PbS", 2), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("PbO", 2), new ChemicalComponent("SO2", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("PH3", 2), new ChemicalComponent("O2", 4) }, new[] { new ChemicalComponent("P2O5", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("SiH4", 1), new ChemicalComponent("O2", 2) }, new[] { new ChemicalComponent("SiO2", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("AsH3", 2), new ChemicalComponent("O2", 3) }, new[] { new ChemicalComponent("As2O3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CO", 1), new ChemicalComponent("Fe2O3", 3) }, new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("Fe3O4", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CO", 1), new ChemicalComponent("Fe3O4", 1) }, new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("FeO", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CO", 1), new ChemicalComponent("FeO", 1) }, new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("Fe", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NO2", 4), new ChemicalComponent("O2", 1), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("HNO3", 4) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("SO2", 2), new ChemicalComponent("O2", 1), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("H2SO4", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("KNO3", 2) }, new[] { new ChemicalComponent("KNO2", 2), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NaNO3", 2) }, new[] { new ChemicalComponent("NaNO2", 2), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Cu(NO3)2", 2) }, new[] { new ChemicalComponent("CuO", 2), new ChemicalComponent("NO2", 4), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Pb(NO3)2", 2) }, new[] { new ChemicalComponent("PbO", 2), new ChemicalComponent("NO2", 4), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("AgNO3", 2) }, new[] { new ChemicalComponent("Ag", 2), new ChemicalComponent("NO2", 2), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NH4NO3", 1) }, new[] { new ChemicalComponent("N2O", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NH4NO2", 1) }, new[] { new ChemicalComponent("N2", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NH4Cl", 1) }, new[] { new ChemicalComponent("NH3", 1), new ChemicalComponent("HCl", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("NaHCO3", 1), new ChemicalComponent("NaOH", 1) }, new[] { new ChemicalComponent("Na2CO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("KHCO3", 1), new ChemicalComponent("KOH", 1) }, new[] { new ChemicalComponent("K2CO3", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Ca(HCO3)2", 1), new ChemicalComponent("Ca(OH)2", 1) }, new[] { new ChemicalComponent("CaCO3", 2), new ChemicalComponent("H2O", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Mg(HCO3)2", 1), new ChemicalComponent("Mg(OH)2", 1) }, new[] { new ChemicalComponent("MgCO3", 2), new ChemicalComponent("H2O", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Fe", 2), new ChemicalComponent("Cl2", 3) }, new[] { new ChemicalComponent("FeCl3", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Na2O2", 2), new ChemicalComponent("CO2", 2) }, new[] { new ChemicalComponent("Na2CO3", 2), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("K2O2", 2), new ChemicalComponent("CO2", 2) }, new[] { new ChemicalComponent("K2CO3", 2), new ChemicalComponent("O2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Na2O2", 2), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("NaOH", 4), new ChemicalComponent("O2", 1) }, Difficulty.Hard),

            new ReactionData(new[] { new ChemicalComponent("BaCl2", 3), new ChemicalComponent("Al2(SO4)3", 1) }, new[] { new ChemicalComponent("BaSO4", 3), new ChemicalComponent("AlCl3", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CaCl2", 3), new ChemicalComponent("Na3PO4", 2) }, new[] { new ChemicalComponent("Ca3(PO4)2", 1), new ChemicalComponent("NaCl", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Ba(NO3)2", 3), new ChemicalComponent("K3PO4", 2) }, new[] { new ChemicalComponent("Ba3(PO4)2", 1), new ChemicalComponent("KNO3", 6) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CuSO4", 3), new ChemicalComponent("Na3PO4", 2) }, new[] { new ChemicalComponent("Cu3(PO4)2", 1), new ChemicalComponent("Na2SO4", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("AgNO3", 3), new ChemicalComponent("Na3PO4", 1) }, new[] { new ChemicalComponent("Ag3PO4", 1), new ChemicalComponent("NaNO3", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("FeCl3", 1), new ChemicalComponent("K3PO4", 1) }, new[] { new ChemicalComponent("FePO4", 1), new ChemicalComponent("KCl", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al2(SO4)3", 1), new ChemicalComponent("NaOH", 6) }, new[] { new ChemicalComponent("Al(OH)3", 2), new ChemicalComponent("Na2SO4", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Fe2(SO4)3", 1), new ChemicalComponent("KOH", 6) }, new[] { new ChemicalComponent("Fe(OH)3", 2), new ChemicalComponent("K2SO4", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("NaOH", 6) }, new[] { new ChemicalComponent("Cr(OH)3", 2), new ChemicalComponent("Na2SO4", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Mg3(PO4)2", 1), new ChemicalComponent("HCl", 6) }, new[] { new ChemicalComponent("MgCl2", 3), new ChemicalComponent("H3PO4", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Ca3(PO4)2", 1), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("CaSO4", 3), new ChemicalComponent("H3PO4", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Na2SiO3", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("NaCl", 2), new ChemicalComponent("H2SiO3", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("K2SiO3", 1), new ChemicalComponent("HNO3", 2) }, new[] { new ChemicalComponent("KNO3", 2), new ChemicalComponent("H2SiO3", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CaSiO3", 1), new ChemicalComponent("HCl", 2) }, new[] { new ChemicalComponent("CaCl2", 1), new ChemicalComponent("H2SiO3", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("PCl3", 1), new ChemicalComponent("H2O", 3) }, new[] { new ChemicalComponent("H3PO3", 1), new ChemicalComponent("HCl", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("PCl5", 1), new ChemicalComponent("H2O", 4) }, new[] { new ChemicalComponent("H3PO4", 1), new ChemicalComponent("HCl", 5) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("SiCl4", 1), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("SiO2", 1), new ChemicalComponent("HCl", 4) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("AlCl3", 1), new ChemicalComponent("H2O", 3) }, new[] { new ChemicalComponent("Al(OH)3", 1), new ChemicalComponent("HCl", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CrCl3", 1), new ChemicalComponent("H2O", 3) }, new[] { new ChemicalComponent("Cr(OH)3", 1), new ChemicalComponent("HCl", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al2S3", 1), new ChemicalComponent("H2O", 6) }, new[] { new ChemicalComponent("Al(OH)3", 2), new ChemicalComponent("H2S", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Mg3N2", 1), new ChemicalComponent("H2O", 6) }, new[] { new ChemicalComponent("Mg(OH)2", 3), new ChemicalComponent("NH3", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Ca3N2", 1), new ChemicalComponent("H2O", 6) }, new[] { new ChemicalComponent("Ca(OH)2", 3), new ChemicalComponent("NH3", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("AlN", 1), new ChemicalComponent("H2O", 3) }, new[] { new ChemicalComponent("Al(OH)3", 1), new ChemicalComponent("NH3", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("CaC2", 1), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("Ca(OH)2", 1), new ChemicalComponent("C2H2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al4C3", 1), new ChemicalComponent("H2O", 12) }, new[] { new ChemicalComponent("Al(OH)3", 4), new ChemicalComponent("CH4", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al2S3", 1), new ChemicalComponent("HCl", 6) }, new[] { new ChemicalComponent("AlCl3", 2), new ChemicalComponent("H2S", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Mg3N2", 1), new ChemicalComponent("HCl", 6) }, new[] { new ChemicalComponent("MgCl2", 3), new ChemicalComponent("NH4Cl", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Ca3PO42", 1), new ChemicalComponent("C", 5), new ChemicalComponent("SiO2", 3) }, new[] { new ChemicalComponent("CaSiO3", 3), new ChemicalComponent("CO", 5), new ChemicalComponent("P", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("P2O5", 1), new ChemicalComponent("HNO3", 6) }, new[] { new ChemicalComponent("HPO3", 2), new ChemicalComponent("N2O5", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("I2O5", 1), new ChemicalComponent("CO", 5) }, new[] { new ChemicalComponent("I2", 1), new ChemicalComponent("CO2", 5) }, Difficulty.Hard),

            new ReactionData(new[] { new ChemicalComponent("Al(OH)3", 1), new ChemicalComponent("NaOH", 1) }, new[] { new ChemicalComponent("Na(Al(OH)4)", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al(OH)3", 1), new ChemicalComponent("KOH", 1) }, new[] { new ChemicalComponent("K(Al(OH)4)", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Zn(OH)2", 1), new ChemicalComponent("NaOH", 2) }, new[] { new ChemicalComponent("Na2(Zn(OH)4)", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Zn(OH)2", 1), new ChemicalComponent("KOH", 2) }, new[] { new ChemicalComponent("K2(Zn(OH)4)", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("NaOH", 6), new ChemicalComponent("H2O", 6) }, new[] { new ChemicalComponent("Na3(Al(OH)6)", 2), new ChemicalComponent("H2", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al", 2), new ChemicalComponent("KOH", 6), new ChemicalComponent("H2O", 6) }, new[] { new ChemicalComponent("K3(Al(OH)6)", 2), new ChemicalComponent("H2", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("NaOH", 2), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("Na2(Zn(OH)4)", 1), new ChemicalComponent("H2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Zn", 1), new ChemicalComponent("KOH", 2), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("K2(Zn(OH)4)", 1), new ChemicalComponent("H2", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("Al2O3", 1), new ChemicalComponent("NaOH", 6), new ChemicalComponent("H2O", 3) }, new[] { new ChemicalComponent("Na3(Al(OH)6)", 2) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("ZnO", 1), new ChemicalComponent("NaOH", 2), new ChemicalComponent("H2O", 1) }, new[] { new ChemicalComponent("Na2(Zn(OH)4)", 1) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("AlCl3", 1), new ChemicalComponent("NaOH", 4) }, new[] { new ChemicalComponent("Na(Al(OH)4)", 1), new ChemicalComponent("NaCl", 3) }, Difficulty.Hard),
            new ReactionData(new[] { new ChemicalComponent("ZnCl2", 1), new ChemicalComponent("NaOH", 4) }, new[] { new ChemicalComponent("Na2(Zn(OH)4)", 1), new ChemicalComponent("NaCl", 2) }, Difficulty.Hard)
        };

        private static readonly ReactionData[] ImpossiblePool = new[] {
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("HCl", 16) }, new[] { new ChemicalComponent("KCl", 2), new ChemicalComponent("MnCl2", 2), new ChemicalComponent("Cl2", 5), new ChemicalComponent("H2O", 8) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("HCl", 14) }, new[] { new ChemicalComponent("KCl", 2), new ChemicalComponent("CrCl3", 2), new ChemicalComponent("Cl2", 3), new ChemicalComponent("H2O", 7) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("FeSO4", 10), new ChemicalComponent("KMnO4", 2), new ChemicalComponent("H2SO4", 8) }, new[] { new ChemicalComponent("Fe2(SO4)3", 5), new ChemicalComponent("MnSO4", 2), new ChemicalComponent("K2SO4", 1), new ChemicalComponent("H2O", 8) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("H2S", 3), new ChemicalComponent("H2SO4", 4) }, new[] { new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("K2SO4", 1), new ChemicalComponent("S", 3), new ChemicalComponent("H2O", 7) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("H2O2", 5), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("MnSO4", 2), new ChemicalComponent("O2", 5), new ChemicalComponent("H2O", 8) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("K2SO3", 5), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("K2SO4", 6), new ChemicalComponent("MnSO4", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("K2SO3", 3), new ChemicalComponent("H2SO4", 4) }, new[] { new ChemicalComponent("K2SO4", 4), new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("H2O", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("KBr", 10), new ChemicalComponent("H2SO4", 8) }, new[] { new ChemicalComponent("K2SO4", 6), new ChemicalComponent("MnSO4", 2), new ChemicalComponent("Br2", 5), new ChemicalComponent("H2O", 8) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("KI", 6), new ChemicalComponent("H2SO4", 7) }, new[] { new ChemicalComponent("K2SO4", 4), new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("I2", 3), new ChemicalComponent("H2O", 7) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Cr2O3", 1), new ChemicalComponent("KNO3", 3), new ChemicalComponent("Na2CO3", 2) }, new[] { new ChemicalComponent("Na2CrO4", 2), new ChemicalComponent("KNO2", 3), new ChemicalComponent("CO2", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("MnO2", 1), new ChemicalComponent("KClO3", 1), new ChemicalComponent("KOH", 6) }, new[] { new ChemicalComponent("K2MnO4", 3), new ChemicalComponent("KCl", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("FeSO4", 6), new ChemicalComponent("H2SO4", 7) }, new[] { new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("Fe2(SO4)3", 3), new ChemicalComponent("K2SO4", 1), new ChemicalComponent("H2O", 7) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("KNO2", 5), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("MnSO4", 2), new ChemicalComponent("KNO3", 5), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("KNO2", 3), new ChemicalComponent("H2SO4", 4) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("KNO3", 3), new ChemicalComponent("H2O", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("H2C2O4", 5), new ChemicalComponent("H2SO4", 3) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("MnSO4", 2), new ChemicalComponent("CO2", 10), new ChemicalComponent("H2O", 8) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2Cr2O7", 1), new ChemicalComponent("H2C2O4", 3), new ChemicalComponent("H2SO4", 4) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("Cr2(SO4)3", 1), new ChemicalComponent("CO2", 6), new ChemicalComponent("H2O", 7) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("Na2SO3", 5), new ChemicalComponent("H2O", 3) }, new[] { new ChemicalComponent("K2SO4", 1), new ChemicalComponent("MnO2", 2), new ChemicalComponent("Na2SO4", 5), new ChemicalComponent("KOH", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("KMnO4", 2), new ChemicalComponent("Na2SO3", 1), new ChemicalComponent("KOH", 2) }, new[] { new ChemicalComponent("K2MnO4", 2), new ChemicalComponent("Na2SO4", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("K2CrO4", 2), new ChemicalComponent("H2O2", 3), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("Cr(OH)3", 2), new ChemicalComponent("KOH", 4), new ChemicalComponent("O2", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("MnSO4", 5), new ChemicalComponent("PbO2", 5), new ChemicalComponent("HNO3", 6) }, new[] { new ChemicalComponent("HMnO4", 2), new ChemicalComponent("Pb(SO4)2", 2), new ChemicalComponent("Pb(NO3)2", 3), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),

            new ReactionData(new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("HNO3", 4) }, new[] { new ChemicalComponent("Cu(NO3)2", 1), new ChemicalComponent("NO2", 2), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Cu", 3), new ChemicalComponent("HNO3", 8) }, new[] { new ChemicalComponent("Cu(NO3)2", 3), new ChemicalComponent("NO", 2), new ChemicalComponent("H2O", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Zn", 4), new ChemicalComponent("HNO3", 10) }, new[] { new ChemicalComponent("Zn(NO3)2", 4), new ChemicalComponent("N2O", 1), new ChemicalComponent("H2O", 5) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Zn", 5), new ChemicalComponent("HNO3", 12) }, new[] { new ChemicalComponent("Zn(NO3)2", 5), new ChemicalComponent("N2", 1), new ChemicalComponent("H2O", 6) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Zn", 4), new ChemicalComponent("HNO3", 10) }, new[] { new ChemicalComponent("Zn(NO3)2", 4), new ChemicalComponent("NH4NO3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Fe", 1), new ChemicalComponent("HNO3", 6) }, new[] { new ChemicalComponent("Fe(NO3)3", 1), new ChemicalComponent("NO2", 3), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Fe", 4), new ChemicalComponent("HNO3", 10) }, new[] { new ChemicalComponent("Fe(NO3)2", 4), new ChemicalComponent("NH4NO3", 1), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Ag", 1), new ChemicalComponent("HNO3", 2) }, new[] { new ChemicalComponent("AgNO3", 1), new ChemicalComponent("NO2", 1), new ChemicalComponent("H2O", 1) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Ag", 3), new ChemicalComponent("HNO3", 4) }, new[] { new ChemicalComponent("AgNO3", 3), new ChemicalComponent("NO", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("P", 3), new ChemicalComponent("HNO3", 5), new ChemicalComponent("H2O", 2) }, new[] { new ChemicalComponent("H3PO4", 3), new ChemicalComponent("NO", 5) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("P", 1), new ChemicalComponent("HNO3", 5) }, new[] { new ChemicalComponent("H3PO4", 1), new ChemicalComponent("NO2", 5), new ChemicalComponent("H2O", 1) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("S", 1), new ChemicalComponent("HNO3", 6) }, new[] { new ChemicalComponent("H2SO4", 1), new ChemicalComponent("NO2", 6), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("S", 3), new ChemicalComponent("HNO3", 4) }, new[] { new ChemicalComponent("H2SO4", 3), new ChemicalComponent("NO", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("C", 1), new ChemicalComponent("HNO3", 4) }, new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("NO2", 4), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Cu", 1), new ChemicalComponent("H2SO4", 2) }, new[] { new ChemicalComponent("CuSO4", 1), new ChemicalComponent("SO2", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Zn", 4), new ChemicalComponent("H2SO4", 5) }, new[] { new ChemicalComponent("ZnSO4", 4), new ChemicalComponent("H2S", 1), new ChemicalComponent("H2O", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Zn", 3), new ChemicalComponent("H2SO4", 4) }, new[] { new ChemicalComponent("ZnSO4", 3), new ChemicalComponent("S", 1), new ChemicalComponent("H2O", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Mg", 4), new ChemicalComponent("H2SO4", 5) }, new[] { new ChemicalComponent("MgSO4", 4), new ChemicalComponent("H2S", 1), new ChemicalComponent("H2O", 4) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("C", 1), new ChemicalComponent("H2SO4", 2) }, new[] { new ChemicalComponent("CO2", 1), new ChemicalComponent("SO2", 2), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("P", 2), new ChemicalComponent("H2SO4", 5) }, new[] { new ChemicalComponent("P2O5", 1), new ChemicalComponent("SO2", 5), new ChemicalComponent("H2O", 5) }, Difficulty.Impossible),

            new ReactionData(new[] { new ChemicalComponent("As2S3", 1), new ChemicalComponent("HNO3", 28), new ChemicalComponent("H2O", 4) }, new[] { new ChemicalComponent("H3AsO4", 2), new ChemicalComponent("H2SO4", 3), new ChemicalComponent("NO", 28) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("FeS", 1), new ChemicalComponent("HNO3", 6) }, new[] { new ChemicalComponent("Fe(NO3)3", 1), new ChemicalComponent("H2SO4", 1), new ChemicalComponent("NO2", 3), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("FeS2", 1), new ChemicalComponent("HNO3", 18) }, new[] { new ChemicalComponent("Fe(NO3)3", 1), new ChemicalComponent("H2SO4", 2), new ChemicalComponent("NO2", 15), new ChemicalComponent("H2O", 7) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Cu2S", 1), new ChemicalComponent("HNO3", 14) }, new[] { new ChemicalComponent("Cu(NO3)2", 2), new ChemicalComponent("H2SO4", 1), new ChemicalComponent("NO2", 10), new ChemicalComponent("H2O", 5) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("CrI3", 2), new ChemicalComponent("Cl2", 27), new ChemicalComponent("KOH", 64) }, new[] { new ChemicalComponent("K2CrO4", 2), new ChemicalComponent("KIO4", 6), new ChemicalComponent("KCl", 54), new ChemicalComponent("H2O", 32) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("FeI2", 2), new ChemicalComponent("Br2", 3), new ChemicalComponent("KOH", 12) }, new[] { new ChemicalComponent("Fe(OH)3", 2), new ChemicalComponent("KIO3", 4), new ChemicalComponent("KBr", 6), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Au", 1), new ChemicalComponent("HNO3", 1), new ChemicalComponent("HCl", 4) }, new[] { new ChemicalComponent("H(AuCl4)", 1), new ChemicalComponent("NO", 1), new ChemicalComponent("H2O", 2) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Pt", 3), new ChemicalComponent("HNO3", 4), new ChemicalComponent("HCl", 18) }, new[] { new ChemicalComponent("H2(PtCl6)", 3), new ChemicalComponent("NO", 4), new ChemicalComponent("H2O", 8) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Cu2O", 1), new ChemicalComponent("HNO3", 6) }, new[] { new ChemicalComponent("Cu(NO3)2", 2), new ChemicalComponent("NO2", 2), new ChemicalComponent("H2O", 3) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("Fe3O4", 1), new ChemicalComponent("HNO3", 10) }, new[] { new ChemicalComponent("Fe(NO3)3", 3), new ChemicalComponent("NO2", 1), new ChemicalComponent("H2O", 5) }, Difficulty.Impossible),
            new ReactionData(new[] { new ChemicalComponent("FeBr2", 6), new ChemicalComponent("K2Cr2O7", 4), new ChemicalComponent("H2SO4", 28) }, new[] { new ChemicalComponent("Fe2(SO4)3", 3), new ChemicalComponent("Br2", 6), new ChemicalComponent("Cr2(SO4)3", 4), new ChemicalComponent("K2SO4", 4), new ChemicalComponent("H2O", 28) }, Difficulty.Impossible)
        };
    }
}